version: '3.3'
services:
  db:
    image: postgres:13.3
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: warp
    volumes:
      - database_folder:/var/lib/postgresql/data
    networks:
      - warp_net
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: production
      DATABASE_HOST: db
    restart: always
    ports:
      - "3222:3000"
    networks:
      - warp_net
    depends_on:
      - db
    volumes:
      - image_folder:/warp/storage/
networks:
  warp_net:
volumes:
  database_folder:
    external:
      name: warp_db
  image_folder:
    external:
      name: warp_images
